import sys
import os
import subprocess
import uuid
import threading
import requests
import customtkinter as ctk
import minecraft_launcher_lib

# Set the modern dark theme for the UI
ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")

def resource_path(relative_path):
    """Get absolute path to resource, works for dev and for PyInstaller"""
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)

class SupersonicLauncher(ctk.CTk):
    def __init__(self):
        super().__init__()

        # UI Window Setup
        self.title("Supersonic Client")
        self.geometry("600x400")
        self.resizable(False, False)

        # Title Label
        self.title_label = ctk.CTkLabel(self, text="SUPERSONIC CLIENT", font=ctk.CTkFont(size=30, weight="bold"))
        self.title_label.pack(pady=(40, 20))

        # Username Input
        self.username_entry = ctk.CTkEntry(self, placeholder_text="Enter Username", width=250, height=40, font=ctk.CTkFont(size=14))
        self.username_entry.pack(pady=20)

        # Play Button
        self.play_button = ctk.CTkButton(self, text="PLAY MINECRAFT", width=250, height=50, font=ctk.CTkFont(size=16, weight="bold"), command=self.start_game_thread)
        self.play_button.pack(pady=10)

        # Status Label (Shows download progress)
        self.status_label = ctk.CTkLabel(self, text="Ready to launch.", font=ctk.CTkFont(size=12), text_color="gray")
        self.status_label.pack(side="bottom", pady=20)

    def update_status(self, text):
        """Updates the status label from the background thread"""
        self.status_label.configure(text=text)
        self.update_idletasks()

    def start_game_thread(self):
        """Starts the download/launch process in a separate thread so UI doesn't freeze"""
        username = self.username_entry.get().strip()
        if not username:
            self.update_status("Error: Please enter a username!")
            return

        self.play_button.configure(state="disabled")
        self.update_status("Preparing to launch...")
        
        # Run launch logic in background
        threading.Thread(target=self.launch_game, args=(username,), daemon=True).start()

    def download_mod(self, url, mods_dir, filename):
        """Helper function to download a mod jar file"""
        self.update_status(f"Downloading Mod: {filename}...")
        try:
            response = requests.get(url, timeout=15)
            if response.status_code == 200:
                with open(os.path.join(mods_dir, filename), "wb") as f:
                    f.write(response.content)
        except Exception as e:
            print(f"Failed to download {filename}: {e}")

    def launch_game(self, username):
        try:
            # Graphics Environment Variables
            os.environ["__GL_THREADED_OPTIMIZATIONS"] = "1"
            
            java_exe = resource_path(os.path.join("jre21", "bin", "java.exe"))
            if not os.path.exists(java_exe):
                self.update_status("Error: Bundled Java 21 not found!")
                self.play_button.configure(state="normal")
                return

            minecraft_directory = minecraft_launcher_lib.utils.get_minecraft_directory()
            base_version = "1.20.4"
            
            # 1. Install Base Minecraft Version
            def print_status(status_text):
                self.update_status(f"Downloading: {status_text}")
                
            callback_dict = {
                "setStatus": print_status,
                "setProgress": lambda p: None,
                "setMax": lambda m: None
            }

            self.update_status(f"Checking Base Minecraft {base_version}...")
            minecraft_launcher_lib.install.install_minecraft_version(base_version, minecraft_directory, callback=callback_dict)
            
            # 2. Install Fabric Loader
            self.update_status("Installing Fabric Optimizer Engine...")
            fabric_version = minecraft_launcher_lib.fabric.get_latest_loader_version()
            minecraft_launcher_lib.fabric.install_fabric(base_version, minecraft_directory, loader_version=fabric_version, callback=callback_dict)
            
            # The actual version ID generated by Fabric
            launch_version = f"fabric-loader-{fabric_version}-{base_version}"

            # 3. Download Performance Mods (Modpack)
            mods_dir = os.path.join(minecraft_directory, "mods")
            if not os.path.exists(mods_dir):
                os.makedirs(mods_dir)

            # Direct download links from Modrinth for 1.20.4 Fabric mods
            modpack = {
                "Sodium.jar": "https://cdn.modrinth.com/data/AANobbMI/versions/99f1I8Lw/sodium-fabric-0.5.8%2Bmc1.20.4.jar",
                "Lithium.jar": "https://cdn.modrinth.com/data/gv9STw84/versions/dtgXv9C6/lithium-fabric-mc1.20.4-0.12.1.jar",
                "Indium.jar": "https://cdn.modrinth.com/data/g96Y6Ofx/versions/L3R6eKIs/indium-1.0.30%2Bmc1.20.4.jar"
            }

            for filename, url in modpack.items():
                if not os.path.exists(os.path.join(mods_dir, filename)):
                    self.download_mod(url, mods_dir, filename)

            self.update_status("Files ready! Generating offline ID...")
            offline_uuid = str(uuid.uuid3(uuid.NAMESPACE_DNS, username))

            # Upgraded Optimization Flags for Max FPS
            options = {
                "username": username,
                "uuid": offline_uuid,
                "token": "",
                "executablePath": java_exe,
                "jvmArguments": [
                    "-Xmx4G",
                    "-XX:+UnlockExperimentalVMOptions",
                    "-XX:+UseG1GC",
                    "-XX:G1NewSizePercent=20",
                    "-XX:G1ReservePercent=20",
                    "-XX:MaxGCPauseMillis=50",
                    "-XX:G1HeapRegionSize=32M",
                    "-Dsun.java2d.d3d=true",
                    "-Dsun.java2d.opengl=false",
                ]
            }

            self.update_status("Launching Modded Game... You can close this window.")
            command = minecraft_launcher_lib.command.get_minecraft_command(launch_version, minecraft_directory, options)
            
            # Start game and close launcher
            subprocess.Popen(command, creationflags=subprocess.CREATE_NO_WINDOW)
            self.destroy() 
            
        except Exception as e:
            self.update_status(f"Error: {e}")
            self.play_button.configure(state="normal")

if __name__ == "__main__":
    app = SupersonicLauncher()
    app.mainloop()
