[; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Supersonic-Client"
#define MyAppVersion "2.5.0"
#define MyAppPublisher "GreekoASC"
#define MyAppURL "Supersonic-Client--Greeko2030.replit.app"
#define MyAppExeName "SupersonicClient.exe"

[Setup]
; App Information
AppId={{8A2B6F9E-3D4C-41A5-B890-ABCDEF123456}
AppName={#Supersonic-Client}
AppVersion={#2.5.0)
AppPublisher={#GreekoASC}
AppPublisherURL={#Supersonic-Client--Greeko2030.replit.app)
AppSupportURL={#Supersonic-Client--Greeko2030.replit.app}
AppUpdatesURL={#Supersonic-Client--Greeko2030.replit.app}

; Installation Directory (Installs to C:\Program Files\Supersonic-Client)
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes

; Output Configuration
OutputDir=Output
OutputBaseFilename=Supersonic-Client-Installer
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern

; Optional: Setup Icon (Uncomment if you have an .ico file)
; SetupIconFile=icon.ico
; UninstallDisplayIcon={app}\{#MyAppExeName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Copy the main executable and all its dependencies generated by PyInstaller
Source: "dist\SupersonicClient\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\SupersonicClient\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Note: The C++ engine (opengl32.dll) will already be included in the dist folder by PyInstaller

[Icons]
; Start Menu and Desktop Shortcuts
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Launch application right after installation finishes
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
