; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Supersonic-Client"
#define MyAppVersion "2.5.0"
#define MyAppPublisher "GreekoASC"
#define MyAppURL "Supersonic-Client--Greeko2030.replit.app"
#define MyAppExeName "SupersonicClient.exe"

[Setup]
; App Information
AppId={{8A2B6F9E-3D4C-41A5-B890-ABCDEF123456}
AppName="{#MyAppName}"
AppVersion="{#MyAppVersion}"
AppPublisher="{#MyAppPublisher}"
AppPublisherURL="{#MyAppURL}"
AppSupportURL="{#MyAppURL}"
AppUpdatesURL="{#MyAppURL}"

; Installation Directory
DefaultDirName="{autopf}\{#MyAppName}"
DisableProgramGroupPage=yes

; Output Configuration
OutputDir="Output"
OutputBaseFilename="Supersonic-Client-Installer"
Compression="lzma2/ultra64"
SolidCompression=yes
WizardStyle="modern"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\SupersonicClient\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\SupersonicClient\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
